image: python:latest

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install flask
  - pip install Flask-Cors

pytest:
  stage: test
  script:
    - pytest

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=elementary-service-py --api-key=$HEROKU_DEPLOY_API_KEY
  artifacts:
    paths:
      - dist/*.whl
